steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/model-api', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/model-api']
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'model-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/model-api'
      - '--region'
      - 'asia-southeast2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--set-env-vars'
      - 'MODEL_BUCKET=hira-bucket,CLOUD_BUCKET_NAME=hira-bucket'

images:
  - 'gcr.io/$PROJECT_ID/model-api'